apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Values.appName }}
    environment: {{ .Values.environment }}
  annotations:
    description: "{{ .Values.description }}"
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        environment: {{ .Values.environment }}
    spec:
      containers:
      - name: {{ .Values.containerName }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.containerPort }}
        env:
{{ toYaml .Values.env | indent 10 }}
        volumeMounts:
        - name: config-volume
          mountPath: {{ .Values.configPath }}
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Release.Name }}-configmap
